# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest
# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
#  - mysql:latest
#  - redis:latest
#  - postgres:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/
  
stages:
  - build
  - deploy

    
build:
  image: node:latest
  stage: build
  tags: 
    - builder
    
  script:
   - npm install -g cnpm --registry=https://registry.npm.taobao.org
   - cnpm install wepy-cli -g
   - cnpm install
   - cnpm run build
   
  artifacts:
    expire_in: 1 week
    paths:
      - dist


deploy_master:
  image: alpine
  stage: deploy
  only:
    - master
  tags: 
    - builder
  script:
    - sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav -e 'ssh -p 579' --delete dist/ www-data@172.26.60.124:/var/www/rank.knogen.com

deploy_dev:
  image: alpine
  stage: deploy
  only:
    - "v1.2_20180912"
  tags: 
    - builder
  script:
    - sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav -e 'ssh -p 579' --delete dist/ www-data@172.26.60.124:/var/www/devrank.knogen.com
